import { readFileSync, existsSync, writeFileSync } from 'node:fs';
import { readdirSync } from 'node:fs';
import { join, basename, extname } from 'node:path';
import type { DaisyConfig, PermissionLevel, MCPProcessConfig, Skill } from '../types.js';

interface OpenCodeAgent {
  name?: string;
  description?: string;
  model?: string;
  temperature?: number;
  permission?: Record<string, string>;
  color?: string;
}

interface OpenCodeConfig {
  default_agent?: string;
  model?: string;
  agent?: Record<string, OpenCodeAgent>;
  skill?: Record<string, unknown>;
  mcp?: Record<string, unknown>;
}

function loadJson(path: string): Record<string, unknown> | null {
  try {
    return JSON.parse(readFileSync(path, 'utf-8'));
  } catch {
    return null;
  }
}

function readMarkdown(path: string): string | null {
  try {
    return readFileSync(path, 'utf-8');
  } catch {
    return null;
  }
}

function castPermissions(p: Record<string, string> | undefined): Record<string, PermissionLevel> | undefined {
  if (!p) return undefined;
  const result: Record<string, PermissionLevel> = {};
  for (const [k, v] of Object.entries(p)) {
    result[k] = v as PermissionLevel;
  }
  return result;
}

function castMcp(mcp: Record<string, unknown> | undefined): Record<string, MCPProcessConfig> | undefined {
  if (!mcp) return undefined;
  const result: Record<string, MCPProcessConfig> = {};
  for (const [k, v] of Object.entries(mcp)) {
    result[k] = v as MCPProcessConfig;
  }
  return result;
}

function castSkill(v: unknown): Skill | null {
  if (typeof v !== 'object' || v === null) return null;
  const obj = v as Record<string, unknown>;
  if (typeof obj.name !== 'string' || !Array.isArray(obj.trigger)) return null;
  return {
    name: obj.name,
    trigger: obj.trigger,
    description: typeof obj.description === 'string' ? obj.description : undefined,
    path: typeof obj.path === 'string' ? obj.path : undefined,
    prompt: typeof obj.prompt === 'string' ? obj.prompt : undefined,
  };
}

export function migrate(cwd: string): void {
  const opencodeJsonPath = join(cwd, 'opencode.json');
  const agentsDir = join(cwd, '.opencode', 'agents');
  const daisyPath = join(cwd, 'daisy.jsonc');

  // Don't overwrite existing daisy config
  if (existsSync(daisyPath)) {
    console.log('daisy.jsonc already exists — skipping migration.');
    return;
  }

  // Load opencode.json
  const opencodeConfig = loadJson(opencodeJsonPath) as OpenCodeConfig | null;
  if (!opencodeConfig) {
    console.log('No opencode.json found — nothing to migrate.');
    return;
  }

  const daisyConfig: DaisyConfig = {
    default_agent: opencodeConfig.default_agent ?? 'default',
    model: opencodeConfig.model ?? 'deepseek/deepseek-chat',
    agent: {},
    skill: {},
    mcp: castMcp(opencodeConfig.mcp),
  };

  // Migrate agents
  if (opencodeConfig.agent) {
    for (const [name, agent] of Object.entries(opencodeConfig.agent)) {
      daisyConfig.agent![name] = {
        description: agent.description,
        model: agent.model,
        temperature: agent.temperature,
        permission: castPermissions(agent.permission),
        color: agent.color,
      };
    }
  }

  // Migrate agent prompts from .opencode/agents/*.md to agent systemPrompt
  if (existsSync(agentsDir)) {
    const files = readdirSync(agentsDir).filter(f => f.endsWith('.md'));
    for (const file of files) {
      const agentName = basename(file, extname(file));
      const content = readMarkdown(join(agentsDir, file));
      if (content && daisyConfig.agent![agentName]) {
        daisyConfig.agent![agentName]!.systemPrompt = content;
      }
    }
  }

  // Migrate existing skills
  if (opencodeConfig.skill) {
    for (const [name, skill] of Object.entries(opencodeConfig.skill)) {
      if (!daisyConfig.skill![name]) {
        const validated = castSkill(skill);
        if (validated) {
          daisyConfig.skill![name] = validated;
        }
      }
    }
  }

  // Write daisy.jsonc (JSON is valid JSONC)
  const json = JSON.stringify(daisyConfig, null, 2);
  writeFileSync(daisyPath, '// Auto-generated by daisy migrate\n' + json + '\n', 'utf-8');

  console.log(`Migrated opencode.json → daisy.jsonc`);
  const agentCount = Object.keys(daisyConfig.agent ?? {}).length;
  const skillCount = Object.keys(daisyConfig.skill ?? {}).length;
  console.log(`  Agents: ${agentCount}, Skills: ${skillCount}`);
}
